### ISSUE TITLE
action -> actionCreator?

### ISSUE THREAD

**Issue by gaearon** [insin/redux-action-utils#1]
One of the most common source of confusion with Flux libraries is that people say “action” when they mean two very different concepts (“action” and “action creator”).

To avoid adding to the confusion, I'd rather rename `action` to `actionCreator` in this API. It's not much more to type, but is much less confusing to the beginners.

What do you think?

**Comment by insin** [comment]
Yes, better to be correct than terse, and you can always alias the functions yourself if you want.

Will publish a new version shortly.

**Comment by gaearon** [comment]
:+1: Thank you!
